import type { Issue } from "../core/types.js";
import { GitHubApiError, GitHubTransport } from "../github/transport.js";
import type { GithubApiToolClient, PrCreateResult, PrStatusResponse } from "./git-types.js";
import type { RepoMatch } from "./repo-router.js";
import { isRecord } from "../utils/type-guards.js";

export type { PrStatusResponse } from "./git-types.js";

/**
 * Type guard that narrows an `unknown` value to `PrStatusResponse`.
 * Always validate the result of `getPrStatus()` with this guard before
 * accessing `.state`, `.merged`, or other typed fields.
 */
export function isPrStatusResponse(value: unknown): value is PrStatusResponse {
  if (!isRecord(value)) return false;
  return (
    (value["state"] === "open" || value["state"] === "closed") &&
    typeof value["merged"] === "boolean" &&
    typeof value["number"] === "number" &&
    typeof value["html_url"] === "string"
  );
}

function isPrCreateResult(value: unknown): value is PrCreateResult {
  if (!isRecord(value)) return false;
  return (
    typeof value["html_url"] === "string" &&
    typeof value["number"] === "number" &&
    (value["state"] === "open" || value["state"] === "closed")
  );
}

export interface GitHubPrClientDeps {
  fetch?: typeof fetch;
  env?: NodeJS.ProcessEnv;
  apiBaseUrl?: string;
  defaultGithubTokenEnv?: string;
}

function isDuplicatePrError(error: unknown): boolean {
  if (!(error instanceof GitHubApiError) || error.status !== 422) {
    return false;
  }
  if (typeof error.payload !== "object" || error.payload === null) {
    return false;
  }
  const payload = error.payload as Record<string, unknown>;

  const message = typeof payload.message === "string" ? payload.message : "";
  if (message.includes("already exists")) return true;

  const errors = payload.errors;
  if (!Array.isArray(errors)) return false;

  return errors.some((err): boolean => {
    if (typeof err !== "object" || err === null) return false;
    const msg = (err as Record<string, unknown>).message;
    return typeof msg === "string" && msg.includes("already exists");
  });
}

/**
 * Builds the pull request body text.
 *
 * When a summary is provided, the body includes a "### Changes" section with the
 * agent-authored bullet list. When absent, a minimal footer is used instead.
 */
function buildPrBody(issueUrl: string | null, summary: string | null): string {
  const closesLine = issueUrl ? `Closes ${issueUrl}` : "";
  const footer = "---\n*Generated by Risoluto*";

  if (summary) {
    const parts = [closesLine, "### Changes", summary, footer].filter((part) => part.length > 0);
    return parts.join("\n\n");
  }

  const parts = [closesLine, footer].filter((part) => part.length > 0);
  return parts.join("\n\n");
}

function parseGithubRepo(repoUrl: string): { owner: string; repo: string } | null {
  const normalized = repoUrl.trim().replace(/\.git$/, "");
  const httpsMatch = /^https?:\/\/github\.com\/([^/]+)\/([^/]+)$/i.exec(normalized);
  if (httpsMatch) {
    return { owner: httpsMatch[1], repo: httpsMatch[2] };
  }
  const sshMatch = /^git@github\.com:([^/]+)\/([^/]+)$/i.exec(normalized);
  if (sshMatch) {
    return { owner: sshMatch[1], repo: sshMatch[2] };
  }
  return null;
}

export class GitHubPrClient implements GithubApiToolClient {
  private readonly defaultGithubTokenEnv: string;
  private readonly transport: GitHubTransport;

  constructor(deps: GitHubPrClientDeps = {}) {
    this.defaultGithubTokenEnv = deps.defaultGithubTokenEnv ?? "GITHUB_TOKEN";
    this.transport = new GitHubTransport({
      fetch: deps.fetch,
      env: deps.env,
      apiBaseUrl: deps.apiBaseUrl,
      defaultTokenEnv: this.defaultGithubTokenEnv,
      authorizationHeaderName: "authorization",
      defaultHeaders: {
        "content-type": "application/json",
        "user-agent": "risoluto",
      },
    });
  }

  async createPullRequest(
    route: RepoMatch,
    issue: Pick<Issue, "identifier" | "title" | "url">,
    branchName: string,
    summary?: string | null,
  ): Promise<PrCreateResult | undefined> {
    const owner = route.githubOwner ?? parseGithubRepo(route.repoUrl)?.owner;
    const repo = route.githubRepo ?? parseGithubRepo(route.repoUrl)?.repo;
    if (!owner || !repo) {
      throw new Error("unable to derive github owner/repo for pull request creation");
    }

    const tokenEnvName = route.githubTokenEnv || this.defaultGithubTokenEnv;
    const prBody = buildPrBody(issue.url ?? null, summary ?? null);
    const body = JSON.stringify({
      title: `${issue.identifier}: ${issue.title}`,
      head: branchName,
      base: route.defaultBranch,
      body: prBody,
    });
    try {
      const created = await this.githubRequest(`/repos/${owner}/${repo}/pulls`, { method: "POST", body }, tokenEnvName);
      return isPrCreateResult(created) ? created : undefined;
    } catch (error) {
      if (!isDuplicatePrError(error)) throw error;
      const existing = await this.githubRequest(
        `/repos/${owner}/${repo}/pulls?head=${owner}:${branchName}&state=open`,
        { method: "GET" },
        tokenEnvName,
      );
      const first = Array.isArray(existing) ? existing[0] : undefined;
      return isPrCreateResult(first) ? first : undefined;
    }
  }

  async addPrComment(input: {
    owner: string;
    repo: string;
    pullNumber: number;
    body: string;
    tokenEnvName?: string;
  }): Promise<unknown> {
    return this.githubRequest(
      `/repos/${input.owner}/${input.repo}/issues/${input.pullNumber}/comments`,
      {
        method: "POST",
        body: JSON.stringify({ body: input.body }),
      },
      input.tokenEnvName,
    );
  }

  async getPrStatus(input: {
    owner: string;
    repo: string;
    pullNumber: number;
    tokenEnvName?: string;
  }): Promise<PrStatusResponse> {
    const raw = await this.githubRequest(
      `/repos/${input.owner}/${input.repo}/pulls/${input.pullNumber}`,
      { method: "GET" },
      input.tokenEnvName,
    );
    if (!isPrStatusResponse(raw)) {
      throw new TypeError(`getPrStatus: unexpected response shape from GitHub API — ${JSON.stringify(raw)}`);
    }
    return raw;
  }

  /**
   * Fetches all reviews for a pull request.
   * Returns the raw GitHub API array (caller is responsible for narrowing).
   */
  async getPrReviews(input: {
    owner: string;
    repo: string;
    pullNumber: number;
    tokenEnvName?: string;
  }): Promise<unknown> {
    return this.githubRequest(
      `/repos/${input.owner}/${input.repo}/pulls/${input.pullNumber}/reviews`,
      { method: "GET" },
      input.tokenEnvName,
    );
  }

  /**
   * Fetches inline line-level review comments for a pull request.
   * Returns the raw GitHub API array (caller is responsible for narrowing).
   */
  async getPrLineComments(input: {
    owner: string;
    repo: string;
    pullNumber: number;
    tokenEnvName?: string;
  }): Promise<unknown> {
    return this.githubRequest(
      `/repos/${input.owner}/${input.repo}/pulls/${input.pullNumber}/comments`,
      { method: "GET" },
      input.tokenEnvName,
    );
  }

  /**
   * Closes an open pull request without merging it.
   * Used by "fresh mode" retries that start from a new branch.
   */
  async closePr(input: { owner: string; repo: string; pullNumber: number; tokenEnvName?: string }): Promise<unknown> {
    return this.githubRequest(
      `/repos/${input.owner}/${input.repo}/pulls/${input.pullNumber}`,
      { method: "PATCH", body: JSON.stringify({ state: "closed" }) },
      input.tokenEnvName,
    );
  }

  /**
   * Requests auto-merge for a pull request via the GitHub GraphQL API.
   *
   * Auto-merge is only *requested* here — GitHub executes the actual merge once
   * all required CI checks pass. If the repository does not have auto-merge
   * enabled at the repo level, GitHub returns a 422 or a GraphQL error; both
   * are treated as non-fatal. Callers should catch and log at warn level.
   *
   * @param owner - Repository owner.
   * @param repo - Repository name.
   * @param pullNumber - Pull request number.
   * @param mergeMethod - Merge strategy to use when auto-merging.
   * @param tokenEnvName - Optional env var name for the GitHub token.
   */
  async requestAutoMerge(
    owner: string,
    repo: string,
    pullNumber: number,
    mergeMethod: "squash" | "merge" | "rebase",
    tokenEnvName?: string,
  ): Promise<void> {
    const resolvedTokenEnv = tokenEnvName ?? this.defaultGithubTokenEnv;
    // The GraphQL mutation requires the PR's global node ID — fetch it first.
    const prData = await this.githubRequest(
      `/repos/${owner}/${repo}/pulls/${pullNumber}`,
      { method: "GET" },
      resolvedTokenEnv,
    );
    if (
      typeof prData !== "object" ||
      prData === null ||
      !("node_id" in prData) ||
      typeof (prData as { node_id?: unknown }).node_id !== "string"
    ) {
      throw new TypeError(`requestAutoMerge: PR response missing node_id for ${owner}/${repo}#${pullNumber}`);
    }
    const pullRequestId = (prData as { node_id: string }).node_id;

    const mutation = `
      mutation EnableAutoMerge($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
        enablePullRequestAutoMerge(input: {
          pullRequestId: $pullRequestId,
          mergeMethod: $mergeMethod
        }) {
          pullRequest {
            autoMergeRequest {
              mergeMethod
            }
          }
        }
      }
    `;

    const { response, payload } = await this.transport.graphql({
      query: mutation,
      variables: { pullRequestId, mergeMethod: mergeMethod.toUpperCase() },
      tokenEnvName: resolvedTokenEnv,
    });

    // 422 means the repository does not have auto-merge enabled — non-fatal.
    if (response.status === 422) {
      return;
    }

    if (!response.ok) {
      throw new GitHubApiError(response.status, payload);
    }

    // GraphQL errors arrive as HTTP 200 with an `errors` array (e.g. auto-merge
    // already enabled, or the repo setting is not configured). Non-fatal — return
    // without throwing so callers can log at warn if needed.
  }

  private async githubRequest(
    pathName: string,
    init: { method: string; body?: string },
    tokenEnvName = this.defaultGithubTokenEnv,
  ): Promise<unknown> {
    return this.transport.request({
      pathName,
      method: init.method,
      body: init.body,
      tokenEnvName,
    });
  }
}
