/**
 * RPC method name constants for the Codex app-server protocol.
 * Use these instead of bare string literals to prevent typos and
 * make cross-file references easy to find.
 */
export const CODEX_METHOD = {
  Initialize: "initialize",
  Initialized: "initialized",
  AccountRead: "account/read",
  AccountLoginStart: "account/login/start",
  AccountLoginCancel: "account/login/cancel",
  AccountLogout: "account/logout",
  AccountRateLimitsRead: "account/rateLimits/read",
  ConfigRequirementsRead: "configRequirements/read",
  ConfigRead: "config/read",
  ConfigMcpServerReload: "config/mcpServer/reload",
  ThreadResume: "thread/resume",
  ThreadRollback: "thread/rollback",
  ThreadStart: "thread/start",
  ThreadRead: "thread/read",
  ThreadList: "thread/list",
  ThreadLoadedList: "thread/loaded/list",
  ThreadFork: "thread/fork",
  ThreadNameSet: "thread/name/set",
  ThreadArchive: "thread/archive",
  ThreadUnarchive: "thread/unarchive",
  ThreadUnsubscribe: "thread/unsubscribe",
  ThreadCompactStart: "thread/compact/start",
  TurnStart: "turn/start",
  TurnSteer: "turn/steer",
  ReviewStart: "review/start",
  CommandExec: "command/exec",
  ExperimentalFeatureList: "experimentalFeature/list",
  CollaborationModeList: "collaborationMode/list",
  McpServerStatusList: "mcpServerStatus/list",
  McpServerOauthLogin: "mcpServer/oauth/login",
  ToolRequestUserInput: "tool/requestUserInput",
  ItemToolRequestUserInput: "item/tool/requestUserInput",
  ModelList: "model/list",
} as const;
